services:
  frontend:
    build:
      context: ./tg-mini-app-master
      dockerfile: Dockerfile
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports: 
      - 5173:5173
    volumes:
      - ./tg-mini-app-master:/app
      - node_modules:/app/node_modules
    networks:
      network:
        ipv4_address: 244.178.44.101

  backend:
    build:
      context: ./CryptoAPI
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 8080:8080
    volumes:
      - ./CryptoAPI/CryptoAPI/Database:/app/Database
    networks:
      network:
        ipv4_address: 244.178.44.102

  telegram_bot:
    build:
      context: ./CryptoBot
      dockerfile: Dockerfile
    restart: always
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
    depends_on:
      - backend
    volumes:
      - ./CryptoBot:/codebase
      - "storage:/storage"
    networks:
      network:
        ipv4_address: 244.178.44.111
  
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./minio-data:/data
    command: server /data

  ssh_tunnels:
    build:
      context: .
      dockerfile: Dockerfile.ssh_tunnels
    volumes:
      - ~/.ssh/serveo_key:/root/.ssh/serveo_key
    entrypoint: /bin/sh /serveo.sh

volumes:
  node_modules: {}
  storage: {}
  minio-data: {}

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 244.178.0.0/16
